.\"-
.\" Copyright (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd August 19, 2021
.Dt GSSC 1
.Os
.Sh NAME
.Nm gssc
.Nd print out device capabilities
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Bf -symbolic
The
.Nm
utility is deprecated.
Users are advised to use
.Xr mgask 1
instead.
.Ef
.Pp
The
.Nm
utility will print the device capabilities in NeXTSTEP plist format.
.Sh HISTORY
The
.Nm
utility first appeared in uikittools on April 6, 2010, written by
.An Jay Qo Saurik Qc Freeman .
Later, it was reimplemented by
.An CoolStar
for the Chimera jailbreak on April 30, 2019.
