.\"-
.\" Copyright (c) 2021
.\"	Cameron Katri.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY CAMERON KATRI AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL CAMERON KATRI OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd August 19, 2021
.Dt UIOPEN 1
.Os
.Sh NAME
.Nm uiopen 
.Nd open an application or url
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl a Ar name 
.Op Fl b Ar id
.Op Fl p Ar path
.Op Fl u Ar url
.Sh DESCRIPTION
The
.Nm
will open the specified app or url on SpringBoard.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl a , -app Ar name
Finds the app with name and opens it.
.It Fl b , -bundleid Ar id
Opens the application with the specified bundle id.
.It Fl h , -help
Prints a help text
.It Fl p , -path Ar path
Opens the application at the specified .app bundle.
.It Fl u , -url Ar url
Opens the specified url in a browser for http or follows the url scheme.
.El
.Sh EXAMPLE
To open github.com in the default browser use:
.Dl "uiopen -u https://github.com"
.Pp
To open the Settings app by name use:
.Dl "uiopen -a Settings"
.Pp
To open the application at /Applications/Sileo.app use:
.Dl "uiopen -p /Application/Sileo.app"
.Sh SEE ALSO
.Xr uicache 1
.Sh HISTORY
The
.Xr uiopen 1
utility first appeared in uikittools on August 18, 2008, written by
.An Jay Freeman .
Then was reimplemented by
.An CoolStar
for the Chimera jailbreak on April 30, 2019.
The
.Fl u ,
.Fl h ,
and
.Fl b
were added to uiopen by absidue on December 25, 2020. The
.Fl a ,
and
.Fl p
flags were added by absidue on August 12, 2021. The
.Nm Ar url
format was deprecated on August 19, 2021.
