.\"-
.\" 版權所有 (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd August 19, 2021
.Dt GSSC 1
.Os
.Sh 名稱
.Nm gssc
.Nd 印出裝置的能力
.Sh 語法
.Nm
.Sh 描述
.Bf -symbolic
這個
.Nm
工具程式已過時
建議用戶使用
.Xr mgask 1
來取代這個工具程式。
.Ef
.Pp
這個
.Nm
工具程式會以NEXTStep plist格式印出裝置的能力。
.Sh
這個
.Nm
工具程式在2010年4月6日首次出現在uikittools，由
.An Jay Qo Saurik Qc Freeman 編寫，
之後，
.An CoolStar
在2019年4月30號為了Chimera越獄重新實現這個工具程式。
