.\"-
.\"Copyright (c) 2020-2021 ProcursusTeam
.\"SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd August 19, 2021
.Dt LDRESTART 1
.Os
.Sh 名称
.Nm ldrestart
.Nd 重新启动现正执行的服务
.Sh 语法
.Nm
.Sh 描述
.Nm
当被使用时，会导致所有launchd服务被重新启动。
.Sh 另见
.Xr sbreload 1
.Sh 历史
这个
.Nm
工具程式在2016年6月22日出现，由
.An Jay Qo Saurik Qc Freeman 编写。
之后
.An CoolStar
在2019年4月30号为Chimera越狱重新实现这工具程式。
