.\"-
.\"Copyright (c) 2020-2021 ProcursusTeam
.\"SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd August 19, 2021
.Dt SBRELOAD 1
.Os
.Sh 名称
.Nm sbreload
.Nd 快速重启主画面
.Sh 语法
.Nm
.Sh 用途
.Nm
当被执行时会重新启动主画面，而且快过用其他方法，例如：
.Xr uicache 1 Fl r .
.Sh 另见
.Xr uicache 1
.Sh 历史
这个
.Nm
工具程式首先在2010年12月3号出现在uikittools中，由
.An Jay Qo Saurik Qc Freeman所编写。
之后
.An CoolStar
在2019年4月30号为了Chimera越狱重新实现这一工具程式。
