.\"-
.\"Copyright (c) 2020-2021 ProcursusTeam
.\"SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd October 18, 2021
.Dt UISAVE 1
.Os
.Sh 名称
.Nm uisave
.Nd 把影像和影片储存到相机胶卷中
.Sh 语法
.Nm
.Ar 档案......
.Sh 描述
把单个或更多个的影像和影片储存到相机胶卷中。
不会移除元数据。
能够储存的影像和影片格式受iOS版本而异。
.Sh 另见
.Xr uishoot 1
.Sh 历史
这个
.Nm
工具程式首先在2021年10月18日在uikittools-ng中出现，由
.An absidue
编写。
